### ISSUE TITLE
Monitoring Operator Unknown Status on Test Cluster

### ISSUE THREAD

**Issue by tssala23** [CCI-MOC/ops-issues#1324]
Message from web interface:
`The monitoring operator may be down or disabled because UpdatingPrometheusFailed, and the components it manages may be unavailable or degraded.`

```
oc get -o yaml clusteroperator monitoring
...
status:
  conditions:
  - lastTransitionTime: "2024-06-13T12:16:00Z"
    message: 'UpdatingPrometheus: client rate limiter Wait returned an error: context
      deadline exceeded'
    reason: UpdatingPrometheusFailed
    status: Unknown
    type: Available
```
