### ISSUE TITLE
IBM Scale Routed Network Issue

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1579]
This issue will serve as the summary and tracker for an ongoing issue involving routed subnets connecting to IBM Scale over our new NVIDIA 5600 fabric.

## Network Diagram

This shows how the 5600s are cabled up to both the Lenovo H100 nodes and to IBM Scale. This is a smaller snippet of a larger network diagram.

<img width="569" alt="Image" src="https://github.com/user-attachments/assets/2ca3ed23-b2d0-4db4-8846-c737aeaa3a5b" />

The 5600s are in an MLAG pair HOWEVER, several connections, including some going to IBM scale, are non-MLAG single port connections.

## Background

* For our ongoing openshift storage experimentation with the IBM scale POC, it was determined that 4x new subnets (`10.8.0.0/18`, `10.8.64.0/18`, `10.8.128.0/18`, `10.8.192.0/18`) would need to be created, all of which needing to be routable to the existing IBM scale high speed network (`10.7.0.0/20`).
* For this, the routers were created on the pair of NVIDIA 5600 switches. These switches run `Cumulus Linux 5.11` and are primarily managed with `nvue`.
* A new VRF `IBMScale` was created on both switches to separate the routing for this from everything else. One switch got `.2` in each subnet, the other `.3`. Finally, VRRP was set up with the `.1` IP being the HA IP for each subnet. Below you will find the VRF config and VRRP config from one of the 5600s. It is duplicated except for the IP changes for the other switch.
```yaml
vrf:
      IBMScale: {}
```

```yaml
      vlan2304:
        ip:
          address:
            10.7.0.2/20: {}
          vrrp:
            virtual-router:
              '10':
                address:
                  10.7.0.1: {}
        vlan: 2304
      vlan2304-2308:
        ip:
          vrf: IBMScale
          vrrp:
            enable: on
      vlan2305:
        ip:
          address:
            10.8.0.2/18: {}
          vrrp:
            virtual-router:
              '15':
                address:
                  10.8.0.1: {}
        vlan: 2305
      vlan2306:
        ip:
          address:
            10.8.64.2/18: {}
          vrrp:
            virtual-router:
              '16':
                address:
                  10.8.64.1: {}
        vlan: 2306
      vlan2307:
        ip:
          address:
            10.8.128.2/18: {}
          vrrp:
            virtual-router:
              '17':
                address:
                  10.8.128.1: {}
        vlan: 2307
      vlan2308:
        ip:
          address:
            10.8.192.2/18: {}
          vrrp:
            virtual-router:
              '18':
                address:
                  10.8.192.1: {}
        vlan: 2308
```
* These switches are MLAGed and have a peer link, but I don't believe that is what is causing the issue (more details on that in the test cases below).
* These are setup as simple static routes. Every subnet on the switch is a direct connection, and static routes are advertised to endpoints via DHCP. This was validated by checking the routing tables of nodes.
* There is no firewall involvement at any stage (disabled across the board for these tesets)
* Each node in IBM scale is connected via aggregated 200G connections to both 5600 switches in MLAG configuration. However, the 6000 A and B (indicated on the diagram above), have several single link non-aggregate connections. We used those in our test cases as well.

## The Problem

It appears that there are some routing inconsistencies between the IBM scale cluster and the H100 nodes. Specifically, IBM scale can ping and receive replies from the H100 nodes, but the inverse is not successful. In addition, IBM scale cannot open TCP connections to the H100 nodes at all despite ICMP ping working fine in that direction.

L2 networks are unaffected. ie. the same nodes used in these tests when put directly on the same vlan/subnet as scale, pings and TCP connections work perfectly fine.

### 1. Openshift -> IBM Scale

First, trying to ping an IP on the IBM side, specifically `10.7.0.111` was attempted but no reply was revealed.
* The openshift node is bare metal as is IBM scale. The openshift side was on a single subnet, in this case `10.8.0.0/18` and the scale node is on `10.7.0.0/18`. There are no other conflicting subnets on either node. Static routes are received from DHCP and routing confirmed to be correct with `ip route` and `ip route get 10.7.0.111`
* Looking at tcpdump on the IBM scale node, it receives the echo request and replies.
* By running a packet capture on the switch, it is also clear that the reply packets from IBM scale make it to the switch
* We do not observe the reply packets going out on the interface to the original H100 node, implying a dropped packet somewhere during switch routing.
* As mentioned, scale also has direct connect non-aggregate connections. The result is the same with these addresses, which leads me to believe this is unrelated to MLAG (especially as the addresses tested are connected to the same switch as openshift so it would not have to traverse the peer link)

### 2. IBM Scale -> Openshift

The inverse
* This test case is successful. The scale node is able to ping and receive replies from the openshift node (same configuration as (1) just inverse).
* This test was used to prove that we do in fact see the packets on the switch coming from scale and going out on the interface to the node, which can serve as a control indicating that our packet capture on the switches should be showing routed packets on success.

### 3. IBM Scale -> Openshift with non-VRRP config

* This test simply changes the static routes to use the `.2` or `.3` IPs on the switches instead of the HA VRRP IP to rule out VRRP involvement. The behavior was the same as test case 2.

### 3. Separate H100 nodes

For this test a separate bare metal cluster was spun up to evaluate a cleaner test environment.
* 2 H100 nodes in 1 cabinet, and 1 in the other were provisioned (this allows for the test case where the packet has to traverse over the peer link of the switches to get to the desired destination)
* Between H100 nodes, all forms of routing works. `10.8` to `10.7`, the inverse, etc. Even tests across racks that traverse the peer link are routed fine.
* The story changes when trying to ping scale again from these new baremetal nodes. We see the same behavior of the packet seemingly being dropped somewhere in the switch after scale replies.

## Other Thoughts

* I wanted to use [what just happened](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/Monitoring-and-Troubleshooting/Network-Troubleshooting/Mellanox-WJH/) on the nvidia switches to find out why the packet was dropped if at all, but I could not get the container to start on the switches.
* There are no drops in interface counters that are relevant as far as I can tell
* Relevant hosts are in the mac table correctly
* L2 communication with the routers on the switches were confirmed for each test (each node can talk to the switch just fine, even for other subnets). For example, a host on the `10.7` network can always talk to a router on the switch on the `10.8` network.
* It is apparent that the issue is only happening with scale and not everything else. However, given that the switch sees the packets coming in from scale I am reluctant to conclude this is a scale issue

example of tcmpdump mirror showing packets coming from scale to the switch (this was captured on the switch itself using [SPAN](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/Monitoring-and-Troubleshooting/Network-Troubleshooting/SPAN-and-ERSPAN/)
```
23:44:48.095256 IP 10.7.0.111 > 10.8.196.127: ICMP echo reply, id 7012, seq 895, length 64
23:44:49.119325 IP 10.7.0.111 > 10.8.196.127: ICMP echo reply, id 7012, seq 896, length 64
23:44:50.143221 IP 10.7.0.111 > 10.8.196.127: ICMP echo reply, id 7012, seq 897, length 64
23:44:51.167182 IP 10.7.0.111 > 10.8.196.127: ICMP echo reply, id 7012, seq 898, length 64
```

## Things to Try
* Tomorrow I am planning on deploying the routing on an upstream dell switch to see if I see the same behavior as when the routers are on the nvidia switches.
