### ISSUE TITLE
MGHPCC: Replace disk and create OSD on research ceph

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#219]
Grad students may get to it first which would be lovely

**Comment by naved001** [comment]
The RAID configuration on neu-15-22 had changed, which means a lot of OSDs were down. After fixing that all OSDs except 1 didn't come online. With 1 OSD down, the cluster is still healthy.

```
[root@kzn-rmon1 ~]# ceph -s
  cluster:
    id:     013f5ba0-52f5-4f73-b201-ce31ba2c3b6a
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum kzn-rmon1,kzn-rmon2,kzn-rmon3
    mgr: kzn-rmon2(active), standbys: kzn-rmon1, kzn-rmon3
    mds: cephrfs-1/1/1 up  {0=kzn-rmon1=up:active}, 2 up:standby
    osd: 63 osds: 62 up, 62 in
    rgw: 2 daemons active
 
  data:
    pools:   17 pools, 1344 pgs
    objects: 1.58 M objects, 4.2 TiB
    usage:   11 TiB used, 23 TiB / 34 TiB avail
    pgs:     1344 active+clean
 
  io:
    client:   0 B/s rd, 1.1 MiB/s wr, 44 op/s rd, 44 op/s wr
[root@kzn-rmon1 ~]# ceph osd tree down
ID  CLASS WEIGHT   TYPE NAME          STATUS REWEIGHT PRI-AFF 
 -1       34.35315 root default                               
-19        3.81702     host neu-15-22                         
 54   hdd  0.54529         osd.54       down        0 1.00000 
```
The OSD is down because the corresponding drive is not available on that host (it should have 8 OSD drives, but there are only 7).

Then I looked at the raid controller of neu-15-22, and noticed that the controller thinks the slot is empty.
![image](https://user-images.githubusercontent.com/20113064/114891765-28ed3e00-9dda-11eb-8313-361e5f1e927f.png)


@hakasapl on your next visit, do you think you could take a look at neu-15-22 and see if that slot 6 is empty? Maybe re-insert the drive if it's there. Thanks!
