### ISSUE TITLE
SSO server down

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#280]
See also https://github.com/operate-first/SRE/issues/332

sso.massopen.cloud was reporting a 500 error this morning. When I logged into the servers, it looks as if the Docker containers on sso1 were not running. 

There was a docker package update this morning around 5:30 that was probably the source of the problem:

```
Jun 09 05:28:02 Updated: docker-common.x86_64 2:1.13.1-208.git7d71120.el7_9
Jun 09 05:28:03 Updated: docker-client.x86_64 2:1.13.1-208.git7d71120.el7_9
Jun 09 05:28:08 Updated: docker.x86_64 2:1.13.1-208.git7d71120.el7_9
```

On sso2, all containers except for the sso container are running. The sso container has exited with an error:

```
# docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                     PORTS                    NAMES
a8fbd1cf26d1        massopencloud/adjutant-moc:0.4.0       "/app/run_adjutant.sh"   4 days ago          Up 6 minutes               0.0.0.0:8081->8080/tcp   adjutant-moc
5ab750e08de1        massopencloud/keycloak-moc:r3          "/opt/jboss/tools/..."   2 months ago        Exited (1) 5 minutes ago                            sso_keycloak-moc_1
571119a845a9        massopencloud/horizon-onboarding:0.2   "/opt/run_horizon.sh"    11 months ago       Up 6 minutes               0.0.0.0:8082->8080/tcp   horizon-onboarding
39861f40f3a9        memcached:1.5.14                       "docker-entrypoint..."   23 months ago       Up 6 minutes               11211/tcp                horizon-memcached
```

@knikolla, is that expected?

**Comment by larsks** [comment]
@knikolla instead of starting the containers via `/etc/rc.local`, can we just set a restart policy on them? This will make Docker responsible for bringing them up, which means they would restart automatically either on system boot or whenever the docker daemon is restarted.

That would look like, e.g:

```
version: "3"

services:
  adjutant-moc:
    container_name: adjutant-moc
    image: massopencloud/adjutant-moc:0.4.0
    environment:
      # DB_HOST is only used by the script waiting for mysql and not adjutant
      # itself. Adjutant database configuration is loaded from adjutant.yaml
      DB_HOST: 172.17.0.1
    ports:
      - "8081:8080"  # host:container
    volumes:
      - "./conf:/etc/adjutant:Z"
      - "./ssh:/.ssh:Z"
    restart: unless-stopped
```
