### ISSUE TITLE
Apply new godaddy certificate to kaizen openstack

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#569]
Part of #566

**Comment by larsks** [comment]
I have updated the kaizen certificates

```
- hosts: controller
  gather_facts: false
  tasks:
    - copy:
        src: massopenall.pem
        dest: /etc/pki/tls/private/overcloud_endpoint.pem
      notify: restart haproxy

  handlers:
    - name: restart haproxy
      shell: docker restart $(docker ps --filter label=name=rhosp13/openstack-haproxy -q)
```

Verification:

```
$ openssl s_client -connect kaizen.massopen.cloud:443 -showcerts < /dev/null | openssl x509 -noout -text | head -10
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2
verify return:1
depth=0 CN = *.massopen.cloud
verify return:1
DONE
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4863353406243520581 (0x437e1a27e454c045)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2
        Validity
            Not Before: May 11 18:09:41 2022 GMT
            Not After : Apr 12 15:49:00 2023 GMT
        Subject: CN = *.massopen.cloud
```
