### ISSUE TITLE
argocd app `cluster-resources-ocp-prod` is degraded

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#630]
maybe related to externalsecrets

![image](https://user-images.githubusercontent.com/20113064/179556394-3d27d6d4-56b6-45be-a25e-2d85474ff2e8.png)

**Comment by joachimweyl** [comment]
it cannot sync

**Comment by naved001** [comment]
looks like two external secrets are not syncing and the status says
```
status:
  lastSync: "2022-05-29T02:11:32.136Z"
  observedGeneration: 1
  status: ERROR, connect ECONNREFUSED 172.30.0.1:443
```

I tried to trigger a secret refresh with this `kubectl annotate es my-es force-sync=$(date +%s) --overwrite` but that did nothing.

The external secrets are definitely in place and I can see them with the aws cli.

**Comment by naved001** [comment]
I deleted the externalsecret `alertmanager-main` to test things. Argocd recreated the externalsecret, but the secret itself was not recreated even after waiting a while. There's no useful information when I run `oc get externalsecret alertmanager-main` or `oc describe` it. I ended up recreating the secret manually but still weird why there is no useful information about this.

**Comment by naved001** [comment]
@larsks looks like externalsecret won't create any new secret. I created a test externalsecret in my namespace `naved-personal` but the secret wasn't created. I am still looking around.

**Comment by naved001** [comment]
I can create that secret on ocp-staging just fine, it's immediately synced.

**Comment by naved001** [comment]
the pod log for external secrets says "status check went boom" lol

```
oc logs pod/moc-kubernetes-external-secrets-64586cfc46-8h5lw -n external-secrets
```
```
{"level":50,"message_time":"2022-08-03T20:19:11.435Z","pid":18,"hostname":"moc-kubernetes-external-secrets-64586cfc46-8h5lw","payload":{},"msg":"status check went boom for naved-personal/naved-test-secret"}
```

**Comment by naved001** [comment]
After restarting the pod I see that it could not load credentials:

```
user/secretreader-ocp-prod is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::574733721584:role/secretreader-cluster1","code":"AccessDenied
```

full message
```
{"level":50,"message_time":"2022-08-03T20:26:40.098Z","pid":18,"hostname":"moc-kubernetes-external-secrets-64586cfc46-kqc7d","payload":{"message":"Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1","code":"CredentialsError","time":"2022-08-03T20:26:40.098Z","requestId":"3614d424-1b2e-43b5-a47f-26fd447ad60c","statusCode":403,"retryable":false,"retryDelay":17.067688640914923,"originalError":{"message":"Could not load credentials from ChainableTemporaryCredentials","code":"CredentialsError","time":"2022-08-03T20:26:40.098Z","requestId":"3614d424-1b2e-43b5-a47f-26fd447ad60c","statusCode":403,"retryable":false,"retryDelay":17.067688640914923,"originalError":{"message":"User: arn:aws:iam::574733721584:user/secretreader-ocp-prod is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::574733721584:role/secretreader-cluster1","code":"AccessDenied","time":"2022-08-03T20:26:40.097Z","requestId":"3614d424-1b2e-43b5-a47f-26fd447ad60c","statusCode":403,"retryable":false,"retryDelay":17.067688640914923}}},"msg":"failure while polling the secret openshift-config/clientsecret-github"}
```

**Comment by naved001** [comment]
@larsks I am not sure what does `secretreader-cluster1` has to do with anything? the user `secretreader-ocp-prod` can read the secrets just fine.

**Comment by naved001** [comment]
well, not sure what happened but I can create an externalsecret correctly

**Comment by larsks** [comment]
@naved001 you mean it just started working again?

**Comment by naved001** [comment]
@larsks looks like it, but I am seeing other issues. `sso-clientsecret-moc` is synced, but `clientsecret-github` is not.
```
naved@Naveds-MacBook-Pro ~ % oc get externalsecret -n openshift-config
NAME                           LAST SYNC   STATUS                                                                                      AGE
clientsecret-github            9s          ERROR, Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1   305d
sso-clientsecret-moc           5s          SUCCESS                                                                                     327d
sso-clientsecret-moc-testing   5s          SUCCESS
```

I dont know who created clientsecret-github, and the specs for it also look weird. There's a reference to some roleArn

```
naved@Naveds-MacBook-Pro ~ % oc get es clientsecret-github -n openshift-config -o yaml |oc neat
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clientsecret-github
  namespace: openshift-config
spec:
  backendType: secretsManager
  data:
  - key: cluster/cluster1/openshift-config/sso-clientsecret-github
    name: clientSecret
  roleArn: arn:aws:iam::574733721584:role/secretreader-cluster1
```
