### ISSUE TITLE
Research ceph troubleshooting

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#753]
The cluster was in a state where all I/O was paused. Apparently this can happen even if a single OSD gets full.

```
[root@kzn-rmon1 ~]# ceph health detail
HEALTH_ERR 2 backfillfull osd(s); 1 full osd(s); 16 pool(s) full
OSD_BACKFILLFULL 2 backfillfull osd(s)
    osd.14 is backfill full
    osd.23 is backfill full
OSD_FULL 1 full osd(s)
    osd.51 is full
POOL_FULL 16 pool(s) full
    pool 'cephrfs' is full (no space)
    pool 'cephrfsmeta' is full (no space)
    pool 'ecrbd_bck' is full (no space)
    pool 'm2' is full (no space)
    pool 'images' is full (no space)
    pool 'vms' is full (no space)
    pool 'rbd_ec' is full (no space)
    pool 'rbd' is full (no space)
    pool '.rgw.root' is full (no space)
    pool 'default.rgw.log' is full (no space)
    pool 'default.rgw.control' is full (no space)
    pool 'default.rgw.meta' is full (no space)
    pool 'default.rgw.buckets.index' is full (no space)
    pool 'default.rgw.buckets.non-ec' is full (no space)
    pool 'volumes' is full (no space)
    pool 'default.rgw.buckets.data' is full (no space)
 ```
 
 The cluster itself had sufficient space (more than 50%).
 ```
 [root@kzn-rmon1 ~]# ceph -s
  cluster:
    id:     013f5ba0-52f5-4f73-b201-ce31ba2c3b6a
    health: HEALTH_ERR
            2 backfillfull osd(s)
            1 full osd(s)
            16 pool(s) full

  services:
    mon: 3 daemons, quorum kzn-rmon1,kzn-rmon2,kzn-rmon3
    mgr: kzn-rmon2(active), standbys: kzn-rmon3, kzn-rmon1
    mds: cephrfs-1/1/1 up  {0=kzn-rmon3=up:active}, 2 up:standby
    osd: 63 osds: 62 up, 62 in
    rgw: 1 daemon active

  data:
    pools:   16 pools, 488 pgs
    objects: 1.56 M objects, 5.0 TiB
    usage:   15 TiB used, 19 TiB / 34 TiB avail
    pgs:     488 active+clean

  io:
    client:   255 B/s rd, 0 op/s rd, 0 op/s wr
 ```
